[package]
name = "sekai-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "sekai"
path = "src/main.rs"

[features]
default = ["backend-sqlite"]
backend-sqlite = ["sekai-app/backend-sqlite"]
backend-mysql = ["sekai-app/backend-mysql"]
backend-postgres = ["sekai-app/backend-postgres"]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
sekai-app.workspace = true
tokio.workspace = true

[package.metadata.cargo-machete]
ignored = ["sekai-app"]
