[package]
name = "sekai-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "sekai"
path = "src/main.rs"

[dependencies]
sekai-core.workspace = true
sekai-engine.workspace = true
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true

[dev-dependencies]
sekai-mca.workspace = true
