[package]
name = "sekai-nbt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sekai-core.workspace = true
thiserror.workspace = true
blake3.workspace = true
fastnbt.workspace = true
flate2.workspace = true
lz4-java-wrc.workspace = true

[dev-dependencies]
serde.workspace = true
