[package]
name = "sekai-nbt"
version = "0.1.0"
edition = "2024"

[lib]
name = "sekai_nbt"
path = "src/lib.rs"

[dependencies]
sekai-core = { path = "../core" }
fastnbt = "2"
flate2 = "1"
lz4-java-wrc = "0.2"
blake3 = "1"
thiserror = "2"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
